### ISSUE TITLE
Initial codebase move to this repo

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#13]
This ticket serves as progress tracker of all the initial tasks:

- [x] move code to this repo
- [x] make build make sense in this repo
- [x] move github issues (ask github)
- [ ] port docs to paradox https://github.com/akka/akka-http/issues/1
  - [x] some steps may require community help
  - [ ] structure documentation
  - [ ] eventually get to the https://github.com/akka/akka-http/issues/11 style
- [x] Setup CI and CLA infra
- [ ] Pick a version number https://github.com/akka/akka-http/issues/3
- [ ] deprecate the directives mixing in trait https://github.com/akka/akka-http/issues/7 ?
- [ ] automate release process (#388)
- [ ] **Stable Release**

**Comment by jrudolph** [comment]
I think #11 is out of scope for now. While moving directive documentation to scaladoc is something we'd like to do eventually, it is also a sizeable amount of work just to implement the preprocessor needed for #11, the actual migration of the documentation itself will need a huge effort to convert from md to scaladoc.

**Comment by ktoso** [comment]
Yeah, agreed - too large scope for initial release

**Comment by jonas** [comment]
@jrudolph @ktoso Without #11 there would be some potentially manual work of fixing the last task in #318 removing 150+ FIXMEs for Scala directive snippets which doesn't currently work.

**Comment by jrudolph** [comment]
Seems we'll have to do some manual work anyways...

**Comment by jonas** [comment]
@jrudolph Should I start copy-pasting scala directive signatures into the docs to resolve #318?

**Comment by jrudolph** [comment]
Couldn't we implement a custom paradox directive to do this automatically?

**Comment by ktoso** [comment]
Closing for now, initial move is done.
