### ISSUE TITLE
Consolidate the remainder of java/scala content in akka-http

### ISSUE THREAD

**Issue by richardimaoka** [akka/akka-http#1624]
Continued from #1290 as the conversation of #1290 got too long.

## Description: 

Like we did on akka/akka#23052  "consolidate java/scala content", let's consolidate the java and scala contents in akka-http, too.

Below is the procedure described by @raboof.

The process is as follows:

* Mention in this issue which pages you're planning to merge 
  * Either the Akka maintainers or @richard-imaoka can update the list below
* Compare a file in `docs/src/main/paradox/java/...` with the same one under `docs/src/main/paradox/scala/....` They should cover the same contents, but one is for Java and the other is for Scala. The 'compare files' feature of IntelliJ IDEA is a nice tool for this.
* Update the file in the `scala` folder to contain both the Scala and Java content. You may use:
`@scala` and `@java` directives for inline text
`@@@ div { .group-scala }` for blocks
[code blocks](http://developer.lightbend.com/docs/paradox/latest/features/groups.html) become tabbed
* Replace the 'java' version of the page with a symlink:
  * Remove the old version (`git rm akka-docs/src/main/paradox/java/...`)
  * Create a symlink (`cd akka-docs/src/main/paradox/java; ln -s ../scala/... ...; cd -`)
  * Add the symlink to git (`git add akka-docs/src/main/paradox/java/...`)
Test your changes (`sbt akka-docs/paradox`, see CONTRIBUTING.md for details, check both the Java and Scala versions)

You could look at https://github.com/akka/akka/pull/23039/files as an example - it's probably best to contribute PR's on a page-per-page basis at least at first. Feel free to let us know if you have any questions/problems!

**Comment by richardimaoka** [comment]
Under **docs/src/main/paradox/java/http/**
* [ ] routing-dsl/index.md (@raboof #1600)


Directives:
* [ ] routing-dsl/directives/cookie-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/scheme-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/cache-condition-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/caching-directives/cache.md (@raboof, first #1579)
* [ ] routing-dsl/directives/caching-directives/index.md
* [ ] routing-dsl/directives/form-field-directives/formFieldList.md
* [ ] routing-dsl/directives/form-field-directives/formField.md
* [ ] routing-dsl/directives/form-field-directives/formFieldMultiMap.md
* [ ] routing-dsl/directives/form-field-directives/formFieldMap.md
* [ ] routing-dsl/directives/form-field-directives/index.md
* [ ] routing-dsl/directives/host-directives/extractHostName.md
* [ ] routing-dsl/directives/host-directives/host.md
* [ ] routing-dsl/directives/host-directives/index.md
* [ ] routing-dsl/directives/header-directives/optionalHeaderValue.md
* [ ] routing-dsl/directives/header-directives/optionalHeaderValuePF.md
* [ ] routing-dsl/directives/header-directives/headerValue.md
* [ ] routing-dsl/directives/header-directives/optionalHeaderValueByType.md
* [ ] routing-dsl/directives/header-directives/checkSameOrigin.md
* [ ] routing-dsl/directives/header-directives/headerValueByType.md
* [ ] routing-dsl/directives/header-directives/headerValueByName.md
* [ ] routing-dsl/directives/header-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/header-directives/optionalHeaderValueByName.md
* [ ] routing-dsl/directives/websocket-directives/extractOfferedWsProtocols.md
* [ ] routing-dsl/directives/websocket-directives/extractUpgradeToWebSocket.md
* [ ] routing-dsl/directives/websocket-directives/handleWebSocketMessagesForOptionalProtocol.md
* [ ] routing-dsl/directives/websocket-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/parameter-directives/parameters.md
* [ ] routing-dsl/directives/parameter-directives/parameterMap.md
* [ ] routing-dsl/directives/parameter-directives/parameterMultiMap.md
* [ ] routing-dsl/directives/parameter-directives/parameter.md
* [ ] routing-dsl/directives/parameter-directives/parameterSeq.md
* [ ] routing-dsl/directives/parameter-directives/index.md
* [ ] routing-dsl/directives/debugging-directives/logResult.md
* [ ] routing-dsl/directives/debugging-directives/logRequest.md
* [ ] routing-dsl/directives/debugging-directives/logRequestResult.md
* [ ] routing-dsl/directives/debugging-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/path-directives/rawPathPrefixTest.md
* [ ] routing-dsl/directives/path-directives/pathPrefixTest.md
* [ ] routing-dsl/directives/path-directives/pathSuffix.md
* [ ] routing-dsl/directives/path-directives/pathEndOrSingleSlash.md
* [ ] routing-dsl/directives/path-directives/rawPathPrefix.md
* [ ] routing-dsl/directives/path-directives/pathSingleSlash.md
* [ ] routing-dsl/directives/path-directives/pathEnd.md
* [ ] routing-dsl/directives/path-directives/index.md
* [ ] routing-dsl/directives/path-directives/pathPrefix.md
* [ ] routing-dsl/directives/path-directives/path.md
* [ ] routing-dsl/directives/method-directives/options.md
* [ ] routing-dsl/directives/method-directives/overrideMethodWithParameter.md
* [ ] routing-dsl/directives/method-directives/post.md
* [ ] routing-dsl/directives/method-directives/delete.md
* [ ] routing-dsl/directives/method-directives/extractMethod.md
* [ ] routing-dsl/directives/method-directives/head.md
* [ ] routing-dsl/directives/method-directives/get.md
* [ ] routing-dsl/directives/method-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/method-directives/method.md
* [ ] routing-dsl/directives/method-directives/put.md
* [ ] routing-dsl/directives/method-directives/patch.md
* [ ] routing-dsl/directives/misc-directives/withSizeLimit.md
* [ ] routing-dsl/directives/misc-directives/extractClientIP.md
* [ ] routing-dsl/directives/misc-directives/rejectEmptyResponse.md
* [ ] routing-dsl/directives/misc-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/misc-directives/validate.md
* [ ] routing-dsl/directives/file-upload-directives/storeUploadedFiles.md
* [ ] routing-dsl/directives/file-upload-directives/fileUploadAll.md
* [ ] routing-dsl/directives/file-upload-directives/fileUpload.md
* [ ] routing-dsl/directives/file-upload-directives/storeUploadedFile.md
* [ ] routing-dsl/directives/file-upload-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/range-directives/withRangeSupport.md
* [ ] routing-dsl/directives/range-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/future-directives/completeOrRecoverWith.md
* [ ] routing-dsl/directives/future-directives/onCompleteWithBreaker.md
* [ ] routing-dsl/directives/future-directives/onSuccess.md
* [ ] routing-dsl/directives/future-directives/onComplete.md
* [ ] routing-dsl/directives/future-directives/index.md
* [ ] routing-dsl/directives/custom-directives.md
* [ ] routing-dsl/directives/security-directives/authorizeAsync.md
* [ ] routing-dsl/directives/security-directives/authenticateOAuth2PF.md
* [ ] routing-dsl/directives/security-directives/authorize.md
* [ ] routing-dsl/directives/security-directives/authenticateBasicPFAsync.md
* [ ] routing-dsl/directives/security-directives/authenticateOrRejectWithChallenge.md
* [ ] routing-dsl/directives/security-directives/authenticateBasic.md
* [ ] routing-dsl/directives/security-directives/authenticateBasicAsync.md
* [ ] routing-dsl/directives/security-directives/authenticateOAuth2Async.md
* [ ] routing-dsl/directives/security-directives/authenticateOAuth2PFAsync.md
* [ ] routing-dsl/directives/security-directives/index.md
* [ ] routing-dsl/directives/security-directives/authenticateBasicPF.md
* [ ] routing-dsl/directives/security-directives/authenticateOAuth2.md
* [ ] routing-dsl/directives/security-directives/extractCredentials.md
* [ ] routing-dsl/directives/alphabetically.md
* [ ] routing-dsl/directives/route-directives/redirect.md
* [ ] routing-dsl/directives/route-directives/complete.md
* [ ] routing-dsl/directives/route-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/file-and-resource-directives/getFromResourceDirectory.md
* [ ] routing-dsl/directives/file-and-resource-directives/listDirectoryContents.md
* [ ] routing-dsl/directives/file-and-resource-directives/getFromBrowseableDirectory.md
* [ ] routing-dsl/directives/file-and-resource-directives/getFromResource.md
* [ ] routing-dsl/directives/file-and-resource-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/by-trait.md
* [ ] routing-dsl/directives/path-directives.md
* [ ] routing-dsl/directives/coding-directives/requestEncodedWith.md
* [ ] routing-dsl/directives/coding-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/timeout-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/timeout-directives/withRequestTimeout.md
* [ ] routing-dsl/directives/marshalling-directives/completeWith.md
* [ ] routing-dsl/directives/marshalling-directives/entity.md
* [ ] routing-dsl/directives/marshalling-directives/handleWith.md
* [ ] routing-dsl/directives/marshalling-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/execution-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/index.md
* [ ] routing-dsl/directives/respond-with-directives/respondWithDefaultHeaders.md
* [ ] routing-dsl/directives/respond-with-directives/index.md (@raboof #1608)
* [ ] routing-dsl/directives/basic-directives/mapRequestContext.md
* [ ] routing-dsl/directives/basic-directives/provide.md
* [ ] routing-dsl/directives/basic-directives/recoverRejections.md
* [ ] routing-dsl/directives/basic-directives/mapRejections.md
* [ ] routing-dsl/directives/basic-directives/mapRequest.md
* [ ] routing-dsl/directives/basic-directives/recoverRejectionsWith.md
* [ ] routing-dsl/directives/basic-directives/mapSettings.md
* [ ] routing-dsl/directives/basic-directives/mapResponseEntity.md
* [ ] routing-dsl/directives/basic-directives/mapRouteResultPF.md
* [ ] routing-dsl/directives/basic-directives/extractUnmatchedPath.md
* [ ] routing-dsl/directives/basic-directives/extract.md
* [ ] routing-dsl/directives/basic-directives/mapRouteResult.md
* [ ] routing-dsl/directives/basic-directives/extractRequest.md
* [ ] routing-dsl/directives/basic-directives/extractDataBytes.md
* [ ] routing-dsl/directives/basic-directives/extractLog.md
* [ ] routing-dsl/directives/basic-directives/mapResponseHeaders.md
* [ ] routing-dsl/directives/basic-directives/mapRouteResultFuture.md
* [ ] routing-dsl/directives/basic-directives/mapResponse.md
* [ ] routing-dsl/directives/basic-directives/mapRouteResultWith.md
* [ ] routing-dsl/directives/basic-directives/withExecutionContext.md
* [ ] routing-dsl/directives/basic-directives/index.md
* [ ] routing-dsl/directives/basic-directives/mapRouteResultWithPF.md
* [ ] routing-dsl/directives/basic-directives/extractParserSettings.md

**Comment by jrudolph** [comment]
Woohoo done!!!! Great work, everyone!

**Comment by ktoso** [comment]
Awesome, and so quickly!
You're all awesome, thanks @richardimaoka @jlprat @jonas @raboof @jrudolph :)

**Comment by raboof** [comment]
🎉 🎅 🎉
