### ISSUE TITLE
Prepare for 10.1.x

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1645]
In previous tickets we discussed and planned the upcoming 10.1.0 release:

 * Future Akka HTTP Versioning And Compatibility (#1305)
 * Prepare for Akka 2.5 (#821)
 * Run tests also against Akka 2.5 (#826)
 * Depend on Akka 2.5 directly, and call it 10.1.x (#1151)

This ticket should track what needs to be done concretely in preparation for the release.

 * [x] Branch off release-10.0.x branch
 * [x] Make sure that releasing still works for upcoming 10.0.x maintenance versions (#1729, #1921)
 * [x] Setup nightly builds for 10.0.x against akka 2.4 and 2.5
 * [x] Build against Akka 2.5 by default (= remove support for Akka 2.4) #1652
 * [x] Set new client pool as the default #1657
 * [x] Make sure version considerations and compatibility guarantee docs are up to date (see also #1106)
 * [x] Remove Akka 2.4 references from documentation #1652 #1728
 * [x] Go through deprecations and make them happen.
   * [x] 2.4.x deprecations addressed in #1656 
   * [x] 10.0.1 and 10.0.2 deprecations in #1668
   * [x] < 10.0.11 deprecations in #1689
   *  ~~ 10.0.11 deprecations~~
 * [x] Adapt Java example to Akka 2.5 (`AbstractActor` changes, see #992)

**Comment by jonas** [comment]
@jrudolph Can you clarify what "go through deprecations and make them happen" means?

Does this only apply to deprecations with version before `10.0.0`, for example there are several deprecations from Akka version `2.4.5`.

**Comment by jonas** [comment]
I suggest adding this ticket to the list: https://github.com/akka/akka-http/issues/992

**Comment by jrudolph** [comment]
> Does this only apply to deprecations with version before 10.0.0, for example there are several deprecations from Akka version 2.4.5.

Definitely for the old ones but I would suggest to also remove the newly deprecated methods (even those from 10.0.11). Affected would be users that update to 10.1.0 which use a third-party library that was built against an Akka HTTP version < 10.0.11. I'd rather be a bit optimistic about it and either hope for library authors to push a compatible version if needed or in the unlikely case that the impact is too big, treat it as a regression that we could still fix in 10.1.1 by reintroducing the deprecated methods. WDYT?

**Comment by jonas** [comment]
I only had the guts to remove deprecations from Akka 2.4.x in my "hygge hakking" session.

**Comment by jrudolph** [comment]
A note regarding our plans: due to potential downstream impact we won't dare to release a final 10.1.0 before Christmas but will probably release an 10.1.0-RC1 for people to play around with. Is probably good practice anyway given the amount of potentially breaking changes.

**Comment by jlprat** [comment]
I'll give a try with some of the 10.0.x deprecations :)

**Comment by jlprat** [comment]
I did remove deprecated methods (since 10.0.1 and 10.0.2) that are mainly renames (they should be doable with scalafix replace feature for example)

**Comment by jrudolph** [comment]
I created https://github.com/akka/akka-http/issues/1680 to discuss future scalafix solutions.

**Comment by rpankajakshan** [comment]
Eagerly waiting for 10.1.0 final - Any indication on the dates ?

**Comment by jlprat** [comment]
Isn't this ticket already finished? Is there something still missing?

**Comment by ktoso** [comment]
Probably only https://github.com/akka/akka-http/issues/1106 remaining
