### ISSUE TITLE
HTTP/2 client-side meta

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3226]
This is a summary ticket for all things missing for public HTTP/2 client support after #3166 has been merged.

 * [ ] review (input) stream handling stages further to make sure they work as expected in more cases
 * [ ] more tests for more complex interactions (multiplexed request/response streams, error cases)
 * [ ] backpressure new user requests when server announced max-concurrent-streams are reached
 * [ ] review whether parsing and rendering need more complete implementations, DRY with server side
 * [ ] public connection-level user API
 * [ ] integration with pool API
 * [ ] revamp stream handling in demux: for less confusion, incoming and outgoing stream implementations should be merged as far as possible
