### ISSUE TITLE
Migrate to Github Actions for all CI and automation needs

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3875]
Jenkins is about to go away and we want to get rid of Travis. Therefore, we'd like to move to Github Actions for all CI needs. This is an umbrella ticket to cover everything that needs to done for a fullmigration.

Current jobs of Jenkins:

 * [x] Basic PR validation (#3866)
 * [ ] Autoformatting (adding a fix commit to PRs)
 * [ ] Taking note of tests
 * [ ] Nightly builds in various configurations
	 * [x] Matrix of JDK and Scala versions -> run in PR validation and master builds on GH actions (#3866)
	 * [x] Matrix of JDK and Akka versions -> run nightlies but only for builds against Akka master
 * [ ] Benchmarks
     * Needs a stable runner to run at to make sure numbers are comparable
     * Results need to be archived and graphs should be published somewhere

Current jobs of Travis:
 * [x] Whitesource check and update (#3876)
 * [x] Publish snapshots and releases (#3876)
 * [x] Publish documentation to gustav (#3876)

**Comment by ennru** [comment]
All we currently need runs well on GitHub workflows now.
